import * as vscode from 'vscode';
import { ApiResult, ButtonConfig, NoteConfig } from './types';

export const DEV_MODE_CONTEXT_KEY = 'buttonfu.isDevelopmentMode';
export const DEV_RESET_API_SMOKE_COMMAND = 'buttonfu.dev.resetApiSmokeData';
export const DEV_CLEAR_API_SMOKE_COMMAND = 'buttonfu.dev.clearApiSmokeData';
export const DEV_CLEAR_DRIVE_NET_SMOKE_COMMAND = 'buttonfu.dev.clearDriveNetSmokeData';

const DEV_API_SMOKE_STATE_KEY = 'buttonfu.dev.apiSmokeState';
const DEV_API_SMOKE_MARKER = '[ButtonFu Dev API Smoke]';
const DEV_API_SMOKE_CATEGORY = 'Development Smoke';
const DEV_API_SMOKE_BUTTON_NAME = 'ButtonFu API Smoke Button';
const DEV_API_SMOKE_NOTE_NAME = 'ButtonFu API Smoke Note';
const DRIVE_NET_SMOKE_BUTTON_COMMAND = 'echo ButtonFu DriveNet smoke test';
const DRIVE_NET_SMOKE_NOTE_CONTENT = 'This note was created by a Drive.NET automation test.';
const DRIVE_NET_WORKFLOW_BUTTON_NAMES = new Set([
    '1. Launch Isolated Smoke Host',
    'Launch Isolated Smoke Host',
    '2. Smoke Tests',
    '2. Drive.NET Smoke Tests',
    'Drive.NET Smoke Tests'
]);
const DRIVE_NET_WORKFLOW_NOTE_NAMES = new Set([
    '3. Smoke Last Result',
    '3. Drive.NET Smoke Last Result',
    'Drive.NET Smoke Last Result'
]);

function buildSmokeButtonDescription(): string {
    return [
        DEV_API_SMOKE_MARKER,
        'Development-only local button created through the registered ButtonFu API commands.',
        'Purpose: verify that agent-style button creation, update, list, and cleanup flows are working end-to-end.',
        'Safe to remove with the "ButtonFu: Dev Clear API Smoke Data" command.'
    ].join(' ');
}

function buildSmokeNoteContent(stage: 'created' | 'updated'): string {
    const lifecycle = stage === 'created'
        ? 'It was created by the development smoke command as the initial API-created note payload.'
        : 'It was then updated by the same development smoke command to prove that API-driven note edits persist correctly.';

    return [
        DEV_API_SMOKE_MARKER,
        '',
        'This local note was generated by the ButtonFu development smoke workflow using the registered `buttonfu.api.createNote` and `buttonfu.api.updateNote` commands.',
        lifecycle,
        '',
        'Why it exists:',
        '- to leave behind a visible note that proves the API can create and modify ButtonFu notes without using the manual editor flow;',
        '- to document that the paired smoke button and this note were created for development validation only;',
        '- to give contributors a safe, fictional artifact they can inspect before cleaning it up.',
        '',
        `Paired button: ${DEV_API_SMOKE_BUTTON_NAME}`,
        'Expected source summary: Agent',
        'Expected createdBy: Agent',
        'Expected lastModifiedBy: Agent',
        'Cleanup command: ButtonFu: Dev Clear API Smoke Data'
    ].join('\n');
}

interface DevApiSmokeState {
    buttonId?: string;
    noteId?: string;
}

export interface DevApiSmokeResult {
    success: boolean;
    button?: ButtonConfig;
    note?: NoteConfig;
    cleanedIds?: string[];
    errors?: string[];
}

function isApiResult<T>(value: unknown): value is ApiResult<T> {
    return !!value && typeof value === 'object' && typeof (value as { success?: unknown }).success === 'boolean';
}

function withFallbackErrors(prefix: string, errors?: string[]): string[] {
    const resolved = errors && errors.length > 0 ? errors : ['Unknown error.'];
    return resolved.map((error) => `${prefix} ${error}`);
}

function isSmokeButton(button: ButtonConfig): boolean {
    return button.locality === 'Local'
        && button.category === DEV_API_SMOKE_CATEGORY
        && button.description.includes(DEV_API_SMOKE_MARKER);
}

function isSmokeNote(note: NoteConfig): boolean {
    return note.locality === 'Local'
        && note.category === DEV_API_SMOKE_CATEGORY
        && note.content.includes(DEV_API_SMOKE_MARKER);
}

function isGuidLikeName(name: string): boolean {
    const trimmed = name.trim();
    return /^[0-9a-f]{32}$/i.test(trimmed)
        || /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(trimmed);
}

function buttonContainsDriveNetSmokeCommand(button: ButtonConfig): boolean {
    if (button.executionText.trim() === DRIVE_NET_SMOKE_BUTTON_COMMAND) {
        return true;
    }

    return (button.terminals ?? []).some((terminal) => terminal.commands.trim() === DRIVE_NET_SMOKE_BUTTON_COMMAND);
}

function isDriveNetSmokeButton(button: ButtonConfig): boolean {
    if (DRIVE_NET_WORKFLOW_BUTTON_NAMES.has(button.name.trim())) {
        return true;
    }

    return isGuidLikeName(button.name) && buttonContainsDriveNetSmokeCommand(button);
}

function isDriveNetSmokeNote(note: NoteConfig): boolean {
    if (DRIVE_NET_WORKFLOW_NOTE_NAMES.has(note.name.trim())) {
        return true;
    }

    return isGuidLikeName(note.name) && note.content.trim() === DRIVE_NET_SMOKE_NOTE_CONTENT;
}

async function executeApiCommand<T>(commandId: string, input?: unknown): Promise<ApiResult<T>> {
    const result = await vscode.commands.executeCommand(commandId, input);
    if (isApiResult<T>(result)) {
        return result;
    }

    return {
        success: false,
        errors: [`Unexpected response from ${commandId}.`]
    };
}

async function listLocalButtons(): Promise<ApiResult<ButtonConfig[]>> {
    return listButtons({ locality: 'Local' });
}

async function listLocalNotes(): Promise<ApiResult<NoteConfig[]>> {
    return listNotes({ locality: 'Local' });
}

async function listButtons(input?: unknown): Promise<ApiResult<ButtonConfig[]>> {
    return executeApiCommand<ButtonConfig[]>('buttonfu.api.listButtons', input);
}

async function listNotes(input?: unknown): Promise<ApiResult<NoteConfig[]>> {
    return executeApiCommand<NoteConfig[]>('buttonfu.api.listNotes', input);
}

async function readSmokeState(workspaceState: vscode.Memento): Promise<DevApiSmokeState> {
    return workspaceState.get<DevApiSmokeState>(DEV_API_SMOKE_STATE_KEY, {});
}

async function writeSmokeState(workspaceState: vscode.Memento, state: DevApiSmokeState | undefined): Promise<void> {
    await workspaceState.update(DEV_API_SMOKE_STATE_KEY, state);
}

async function gatherSmokeIds(workspaceState: vscode.Memento): Promise<{ buttonIds: string[]; noteIds: string[]; errors: string[]; }> {
    const state = await readSmokeState(workspaceState);
    const buttonIds = new Set<string>();
    const noteIds = new Set<string>();
    const errors: string[] = [];

    if (state.buttonId) {
        buttonIds.add(state.buttonId);
    }
    if (state.noteId) {
        noteIds.add(state.noteId);
    }

    const listedButtons = await listLocalButtons();
    if (listedButtons.success) {
        for (const button of listedButtons.data ?? []) {
            if (isSmokeButton(button)) {
                buttonIds.add(button.id);
            }
        }
    } else {
        errors.push(...withFallbackErrors('Failed to list local buttons.', listedButtons.errors));
    }

    const listedNotes = await listLocalNotes();
    if (listedNotes.success) {
        for (const note of listedNotes.data ?? []) {
            if (isSmokeNote(note)) {
                noteIds.add(note.id);
            }
        }
    } else {
        errors.push(...withFallbackErrors('Failed to list local notes.', listedNotes.errors));
    }

    return {
        buttonIds: [...buttonIds],
        noteIds: [...noteIds],
        errors
    };
}

export async function clearDevApiSmokeData(context: vscode.ExtensionContext, options?: { silent?: boolean }): Promise<DevApiSmokeResult> {
    const candidates = await gatherSmokeIds(context.workspaceState);
    const errors = [...candidates.errors];
    const cleanedIds: string[] = [];

    for (const buttonId of candidates.buttonIds) {
        const deleted = await executeApiCommand<{ id: string }>('buttonfu.api.deleteButton', buttonId);
        if (deleted.success) {
            cleanedIds.push(buttonId);
            continue;
        }

        const missing = deleted.errors?.some((error) => error.includes('not found'));
        if (!missing) {
            errors.push(...withFallbackErrors(`Failed to delete smoke button ${buttonId}.`, deleted.errors));
        }
    }

    for (const noteId of candidates.noteIds) {
        const deleted = await executeApiCommand<{ id: string }>('buttonfu.api.deleteNote', noteId);
        if (deleted.success) {
            cleanedIds.push(noteId);
            continue;
        }

        const missing = deleted.errors?.some((error) => error.includes('not found'));
        if (!missing) {
            errors.push(...withFallbackErrors(`Failed to delete smoke note ${noteId}.`, deleted.errors));
        }
    }

    await writeSmokeState(context.workspaceState, undefined);

    if (!options?.silent) {
        if (errors.length > 0) {
            void vscode.window.showErrorMessage(`ButtonFu dev API smoke cleanup failed. ${errors.join(' ')}`);
        } else {
            void vscode.window.showInformationMessage(`ButtonFu dev API smoke cleanup removed ${cleanedIds.length} item(s).`);
        }
    }

    return {
        success: errors.length === 0,
        cleanedIds,
        errors: errors.length > 0 ? errors : undefined
    };
}

export async function clearDriveNetSmokeData(options?: { silent?: boolean }): Promise<DevApiSmokeResult> {
    const errors: string[] = [];
    const cleanedIds: string[] = [];

    const listedButtons = await listButtons();
    if (listedButtons.success) {
        for (const button of listedButtons.data ?? []) {
            if (!isDriveNetSmokeButton(button)) {
                continue;
            }

            const deleted = await executeApiCommand<{ id: string }>('buttonfu.api.deleteButton', button.id);
            if (deleted.success) {
                cleanedIds.push(button.id);
                continue;
            }

            errors.push(...withFallbackErrors(`Failed to delete Drive.NET smoke button ${button.id}.`, deleted.errors));
        }
    } else {
        errors.push(...withFallbackErrors('Failed to list buttons for Drive.NET smoke cleanup.', listedButtons.errors));
    }

    const listedNotes = await listNotes();
    if (listedNotes.success) {
        for (const note of listedNotes.data ?? []) {
            if (!isDriveNetSmokeNote(note)) {
                continue;
            }

            const deleted = await executeApiCommand<{ id: string }>('buttonfu.api.deleteNote', note.id);
            if (deleted.success) {
                cleanedIds.push(note.id);
                continue;
            }

            errors.push(...withFallbackErrors(`Failed to delete Drive.NET smoke note ${note.id}.`, deleted.errors));
        }
    } else {
        errors.push(...withFallbackErrors('Failed to list notes for Drive.NET smoke cleanup.', listedNotes.errors));
    }

    if (!options?.silent) {
        if (errors.length > 0) {
            void vscode.window.showErrorMessage(`ButtonFu Drive.NET smoke cleanup failed. ${errors.join(' ')}`);
        } else {
            void vscode.window.showInformationMessage(`ButtonFu Drive.NET smoke cleanup removed ${cleanedIds.length} item(s).`);
        }
    }

    return {
        success: errors.length === 0,
        cleanedIds,
        errors: errors.length > 0 ? errors : undefined
    };
}

async function rollbackCreatedItems(context: vscode.ExtensionContext, createdButtonId?: string, createdNoteId?: string): Promise<void> {
    if (createdButtonId) {
        await executeApiCommand<{ id: string }>('buttonfu.api.deleteButton', createdButtonId);
    }
    if (createdNoteId) {
        await executeApiCommand<{ id: string }>('buttonfu.api.deleteNote', createdNoteId);
    }
    await writeSmokeState(context.workspaceState, undefined);
}

export async function resetDevApiSmokeData(
    context: vscode.ExtensionContext,
    input?: { openEditors?: boolean }
): Promise<DevApiSmokeResult> {
    const shouldOpenEditors = input?.openEditors ?? true;
    const cleanup = await clearDevApiSmokeData(context, { silent: true });
    if (!cleanup.success) {
        void vscode.window.showErrorMessage(`ButtonFu dev API smoke reset failed during cleanup. ${(cleanup.errors ?? []).join(' ')}`);
        return cleanup;
    }

    const buttonCreate = await executeApiCommand<ButtonConfig>('buttonfu.api.createButton', {
        locality: 'Local',
        name: DEV_API_SMOKE_BUTTON_NAME,
        description: buildSmokeButtonDescription(),
        type: 'TerminalCommand',
        executionText: 'echo ButtonFu API smoke button',
        category: DEV_API_SMOKE_CATEGORY,
        icon: 'beaker',
        openEditor: shouldOpenEditors
    });
    if (!buttonCreate.success || !buttonCreate.data) {
        const errors = withFallbackErrors('Failed to create the smoke button.', buttonCreate.errors);
        void vscode.window.showErrorMessage(`ButtonFu dev API smoke reset failed. ${errors.join(' ')}`);
        return {
            success: false,
            cleanedIds: cleanup.cleanedIds,
            errors
        };
    }

    const noteCreate = await executeApiCommand<NoteConfig>('buttonfu.api.createNote', {
        locality: 'Local',
        name: DEV_API_SMOKE_NOTE_NAME,
        content: buildSmokeNoteContent('created'),
        format: 'PlainText',
        defaultAction: 'open',
        category: DEV_API_SMOKE_CATEGORY,
        icon: 'note',
        openEditor: shouldOpenEditors
    });
    if (!noteCreate.success || !noteCreate.data) {
        await rollbackCreatedItems(context, buttonCreate.data.id);
        const errors = withFallbackErrors('Failed to create the smoke note.', noteCreate.errors);
        void vscode.window.showErrorMessage(`ButtonFu dev API smoke reset failed. ${errors.join(' ')}`);
        return {
            success: false,
            cleanedIds: cleanup.cleanedIds,
            errors
        };
    }

    const buttonUpdate = await executeApiCommand<ButtonConfig>('buttonfu.api.updateButton', {
        id: buttonCreate.data.id,
        description: buildSmokeButtonDescription()
    });
    if (!buttonUpdate.success || !buttonUpdate.data) {
        await rollbackCreatedItems(context, buttonCreate.data.id, noteCreate.data.id);
        const errors = withFallbackErrors('Failed to update the smoke button.', buttonUpdate.errors);
        void vscode.window.showErrorMessage(`ButtonFu dev API smoke reset failed. ${errors.join(' ')}`);
        return {
            success: false,
            cleanedIds: cleanup.cleanedIds,
            errors
        };
    }

    const noteUpdate = await executeApiCommand<NoteConfig>('buttonfu.api.updateNote', {
        id: noteCreate.data.id,
        content: buildSmokeNoteContent('updated')
    });
    if (!noteUpdate.success || !noteUpdate.data) {
        await rollbackCreatedItems(context, buttonCreate.data.id, noteCreate.data.id);
        const errors = withFallbackErrors('Failed to update the smoke note.', noteUpdate.errors);
        void vscode.window.showErrorMessage(`ButtonFu dev API smoke reset failed. ${errors.join(' ')}`);
        return {
            success: false,
            cleanedIds: cleanup.cleanedIds,
            errors
        };
    }

    const updatedButton = buttonUpdate.data;
    const updatedNote = noteUpdate.data;

    const buttonGet = await executeApiCommand<ButtonConfig>('buttonfu.api.getButton', updatedButton.id);
    const noteGet = await executeApiCommand<NoteConfig>('buttonfu.api.getNote', updatedNote.id);
    const listedButtons = await listLocalButtons();
    const listedNotes = await listLocalNotes();
    const errors: string[] = [];

    if (!buttonGet.success || !buttonGet.data) {
        errors.push(...withFallbackErrors('Failed to fetch the smoke button after update.', buttonGet.errors));
    }
    if (!noteGet.success || !noteGet.data) {
        errors.push(...withFallbackErrors('Failed to fetch the smoke note after update.', noteGet.errors));
    }
    if (!listedButtons.success || !(listedButtons.data ?? []).some((button) => button.id === updatedButton.id)) {
        errors.push(...withFallbackErrors('Failed to verify the smoke button in the local list.', listedButtons.errors));
    }
    if (!listedNotes.success || !(listedNotes.data ?? []).some((note) => note.id === updatedNote.id)) {
        errors.push(...withFallbackErrors('Failed to verify the smoke note in the local list.', listedNotes.errors));
    }

    if (errors.length > 0) {
        await rollbackCreatedItems(context, updatedButton.id, updatedNote.id);
        void vscode.window.showErrorMessage(`ButtonFu dev API smoke reset failed. ${errors.join(' ')}`);
        return {
            success: false,
            cleanedIds: cleanup.cleanedIds,
            errors
        };
    }

    await writeSmokeState(context.workspaceState, {
        buttonId: updatedButton.id,
        noteId: updatedNote.id
    });

    void vscode.window.showInformationMessage('ButtonFu dev API smoke data was reset using the registered API commands.');
    return {
        success: true,
        cleanedIds: cleanup.cleanedIds,
        button: updatedButton,
        note: updatedNote
    };
}

